### ISSUE TITLE
Adding library causing "android.support.design.widget.NavigationView" error

### ISSUE THREAD

**Issue by kumar-aakash86** [medyo/android-about-page#44]
When I add this library in app.bundle my app starts crashing. I didn't even change a single line of code except adding compile path in app.bundle.

Error log is as below

> java.lang.RuntimeException: Unable to start activity ComponentInfo{andro.rdx.pharmac/andro.rdx.pharmac.activity.DashboardActivity}: android.view.InflateException: Binary XML file line #147: Error inflating class android.support.design.widget.NavigationView
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2200)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2249)
                                                                     at android.app.ActivityThread.access$800(ActivityThread.java:141)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1212)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:136)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5113)
                                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
                                                                     at dalvik.system.NativeStart.main(Native Method)

removing the compile path resolve this error.
Did anyone else faced this issue ?

Here is the app's config info
compileSdkVersion 23
buildToolsVersion "23.0.2"
minSdkVersion 15
targetSdkVersion 23

compile 'com.android.support:appcompat-v7:23.1.0'
compile 'com.android.support:design:23.1.0'

**Comment by medyo** [comment]
Hi @kumar-aakash86,

I think it's caused by the use of the latest AppCompat version. try to exclude it : 

~~~gradle
compile ('com.github.medyo:android-about-page:+'){
     exclude group: 'com.android.support', module:'appcompat-v7'
}
~~~

**Comment by kumar-aakash86** [comment]
Hi @medyo,
I tried your suggestion & its not showing that error now.
But when I trying to add AboutPage code its showing following error.

> java.lang.NoClassDefFoundError: android.support.graphics.drawable.VectorDrawableCompat
                                                                     at mehdi.sakout.aboutpage.AboutPage.createItem(AboutPage.java:364)
                                                                     at mehdi.sakout.aboutpage.AboutPage.addItem(AboutPage.java:241)
                                                                     at mehdi.sakout.aboutpage.AboutPage.addEmail(AboutPage.java:59)
                                                                     at andro.rdx.pharmac.activity.AboutActivity$override.onCreate(AboutActivity.java:39)
                                                                     at andro.rdx.pharmac.activity.AboutActivity$override.access$dispatch(AboutActivity.java)
                                                                     at andro.rdx.pharmac.activity.AboutActivity.onCreate(AboutActivity.java:0)
                                                                     at android.app.Activity.performCreate(Activity.java:5248)
                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2164)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2249)
                                                                     at android.app.ActivityThread.access$800(ActivityThread.java:141)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1212)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:136)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5113)
                                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
                                                                     at dalvik.system.NativeStart.main(Native Method)


Its because of the removal of appcompact.

**Comment by medyo** [comment]
upgrade your Appcompat to `23.2.0`

**Comment by kumar-aakash86** [comment]
Appcompact 23.2.0 is buggy, its created some more view errors.
Upgraded to 23.2.1. Everything seems to working fine now.

Thanks for the help.
Nice library.
