### ISSUE TITLE
Crash on API 16

### ISSUE THREAD

**Issue by DreierF** [medyo/android-about-page#50]
Hi,

first of all thanks for this awesome library!
Unfortunately I'm experiencing a crash when using the library on API level 16. On API 21 everything works fine.

Here is the relevant code for creating the about page
```
new AboutPage(getContext())
                .setImage(R.drawable.logo)
                .addItem(new Element(null, getString(R.string.share_with_friends), R.drawable.about_icon_share))
                .create();
```

I'm using the android gradle plugin 2.1.0. `about_icon_share` is a vector drawable. The library seems to assume that I'm using `vectorDrawables.useSupportLibrary = true`, which is not the case.

> FATAL EXCEPTION: main
java.lang.RuntimeException: Unable to start activity ComponentInfo{de.dreier.mytargets/de.dreier.mytargets.activities.SimpleFragmentActivity$AboutActivity}: android.content.res.Resources$NotFoundException: File res/drawable-xhdpi-v4/about_icon_share.png from xml type xml resource ID #0x7f020057
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2059)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)
at android.app.ActivityThread.access$600(ActivityThread.java:130)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4745)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
at dalvik.system.NativeStart.main(Native Method)
Caused by: android.content.res.Resources$NotFoundException: File res/drawable-xhdpi-v4/about_icon_share.png from xml type xml resource ID #0x7f020057
at android.content.res.Resources.loadXmlResourceParser(Resources.java:2145)
at android.content.res.Resources.loadXmlResourceParser(Resources.java:2100)
at android.content.res.Resources.getXml(Resources.java:901)
at android.support.graphics.drawable.VectorDrawableCompat.create(VectorDrawableCompat.java:408)
at mehdi.sakout.aboutpage.AboutPage.createItem(AboutPage.java:364)
at mehdi.sakout.aboutpage.AboutPage.addItem(AboutPage.java:241)
at de.dreier.mytargets.fragments.AboutFragment.onCreateView(AboutFragment.java:91)
at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742)
at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:339)
at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:601)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1163)
at android.app.Activity.performStart(Activity.java:5018)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2032)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084) 
at android.app.ActivityThread.access$600(ActivityThread.java:130) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195) 
at android.os.Handler.dispatchMessage(Handler.java:99) 
at android.os.Looper.loop(Looper.java:137) 
at android.app.ActivityThread.main(ActivityThread.java:4745) 
at java.lang.reflect.Method.invokeNative(Native Method) 
at java.lang.reflect.Method.invoke(Method.java:511) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
at dalvik.system.NativeStart.main(Native Method) 
Caused by: java.io.FileNotFoundException: Corrupt XML binary file
at android.content.res.AssetManager.openXmlAssetNative(Native Method)
at android.content.res.AssetManager.openXmlBlockAsset(AssetManager.java:487)
at android.content.res.Resources.loadXmlResourceParser(Resources.java:2127)
at android.content.res.Resources.loadXmlResourceParser(Resources.java:2100) 
at android.content.res.Resources.getXml(Resources.java:901) 
at android.support.graphics.drawable.VectorDrawableCompat.create(VectorDrawableCompat.java:408) 
at mehdi.sakout.aboutpage.AboutPage.createItem(AboutPage.java:364) 
at mehdi.sakout.aboutpage.AboutPage.addItem(AboutPage.java:241) 
at de.dreier.mytargets.fragments.AboutFragment.onCreateView(AboutFragment.java:91) 
at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974) 
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067) 
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252) 
at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742) 
at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617) 
at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:339) 
at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:601) 
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1163) 
at android.app.Activity.performStart(Activity.java:5018) 
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2032) 
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084) 
at android.app.ActivityThread.access$600(ActivityThread.java:130) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195) 
at android.os.Handler.dispatchMessage(Handler.java:99) 
at android.os.Looper.loop(Looper.java:137) 
at android.app.ActivityThread.main(ActivityThread.java:4745) 
at java.lang.reflect.Method.invokeNative(Native Method) 
at java.lang.reflect.Method.invoke(Method.java:511) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
at dalvik.system.NativeStart.main(Native Method)

You can find the code at https://github.com/dreierf/mytargets

Thanks in advance

**Comment by medyo** [comment]
Hi @DreierF, I just tried the library samples on API 16, everything works fine.
Try to comment the whole `android-about-page` code from your fragment and check if it's really the cause.

**Comment by DreierF** [comment]
Hi @medyo, thanks for your quick reply. If I remove the `addItem` line everything works fine. If I add it the crash happens :-/

**Comment by medyo** [comment]
try to add `addItem` without setting an icon, if it doesn't crash, that means two things, whether the drawable is corrupted, or a compatibily issue at : 
https://github.com/medyo/android-about-page/blob/master/library/src/main/java/mehdi/sakout/aboutpage/AboutPage.java#L359

**Comment by DreierF** [comment]
When icon is set to null it works.

**Comment by DreierF** [comment]
I just tested compiling with `vectorDrawables.useSupportLibrary = true`, than it works on jelly bean (API 16).
>android.content.res.Resources$NotFoundException: File res/drawable-xhdpi-v4/about_icon_share.png from xml type xml resource ID #0x7f020057
This also indicates that VectorDrawableCompat.create expects the resource to be a vector drawable instead of a png.

**Comment by DreierF** [comment]
I have now "solved" it by enabling `vectorDrawables.useSupportLibrary = true` for the whole project.
So if nobody else needs this to run with pngs you can close the issue, but I'd suggest to add a hint on this to the readme.

**Comment by juandiegoapps** [comment]
Hi. I'm trying to implement it into my app, but How do I have to do it? I'm trying different ways, but it is crashing!

**Comment by sourabh48** [comment]
i want to use it in fragment is it possible?
