### ISSUE TITLE
Info button

### ISSUE THREAD

**Issue by bahmet** [medyo/android-about-page#69]
Hi,
i would like to use your about page in my very basic application.
it is a webview application. currently i have added menu item  on the action bar and call  layout with setContentView(R.layout.activity_info);
is there an easy way to call your about page.  beginners like me :)
thanks

**Comment by medyo** [comment]
Hi @bahmet,

Take a look at this sample : https://github.com/medyo/android-about-page/blob/master/app/src/main/java/mehdi/sakout/aboutpage/sample/MainActivity.java
it's exactly what you need.

**Comment by bahmet** [comment]
Hello Mehdi,

Thanks for your response,

since i am a beginner to android thing,

i have copied all your resources to the related directories manually, i do not know an easy way,

then, i added your code to the button item action

""public boolean onOptionsItemSelected(MenuItem item) {

   switch (item.getItemId()) {


       case R.id.action_favorite:

Element adsElement = new Element();
adsElement.setTitle("Advertise with us");

View aboutPage = new AboutPage(this)
.isRTL(false)
.setImage(R.drawable.dummy_image)
.addItem(new Element().setTitle("Version 6.2"))
.addItem(adsElement)
.addGroup("Connect with us")
.addEmail("elmehdi.sakout@gmail.com")
.addWebsite("http://medyo.github.io/")
.addFacebook("the.medy")
.addTwitter("medyo80")
.addYoutube("UCdPQtdWIsg7_pi4mrRu46vA")
.addPlayStore("com.ideashower.readitlater.pro")
.addInstagram("medyo80")
.addGitHub("medyo")
.create();

setContentView(aboutPage);
return true;""

my app crashed as soon as i click the menu item, below is the info that i got from debugger....


i really appreciate your work, thanks..


E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.dijitalyayincim.cekmekoy.cekmekoy_web, PID: 28870
                  android.content.res.Resources$NotFoundException: File res/drawable-xxhdpi-v4/about_icon_email.png from xml type xml resource ID #0x7f020054. If the resource you are trying to use is a vector resource, you may be referencing it in an unsupported way. See AppCompatDelegate.setCompatVectorFromResourcesEnabled() for more info.
                      at android.content.res.Resources.loadXmlResourceParser(Resources.java:2396)
                      at android.content.res.Resources.loadXmlResourceParser(Resources.java:2351)
                      at android.content.res.Resources.getXml(Resources.java:1028)
                      at android.support.graphics.drawable.VectorDrawableCompat.create(VectorDrawableCompat.java:413)
                      at com.dijitalyayincim.cekmekoy.cekmekoy_web.AboutPage.createItem(AboutPage.java:360)
                      at com.dijitalyayincim.cekmekoy.cekmekoy_web.AboutPage.addItem(AboutPage.java:243)
                      at com.dijitalyayincim.cekmekoy.cekmekoy_web.AboutPage.addEmail(AboutPage.java:61)
                      at com.dijitalyayincim.cekmekoy.cekmekoy_web.MainActivity.onOptionsItemSelected(MainActivity.java:58)
                      at android.app.Activity.onMenuItemSelected(Activity.java:2644)
                      at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:406)
                      at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:195)
                      at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:103)
                      at android.support.v7.app.AppCompatDelegateImplV9.onMenuItemSelected(AppCompatDelegateImplV9.java:667)
                      at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:810)
                      at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
                      at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:957)
                      at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:947)
                      at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:616)
                      at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:153)
                      at android.view.View.performClick(View.java:4442)
                      at android.view.View$PerformClick.run(View.java:18473)
                      at android.os.Handler.handleCallback(Handler.java:733)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:136)
                      at android.app.ActivityThread.main(ActivityThread.java:5105)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:515)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
                      at dalvik.system.NativeStart.main(Native Method)
                   Caused by: java.io.FileNotFoundException: Corrupt XML binary file
                      at android.content.res.AssetManager.openXmlAssetNative(Native Method)
                      at android.content.res.AssetManager.openXmlBlockAsset(AssetManager.java:495)
                      at android.content.res.Resources.loadXmlResourceParser(Resources.java:2378)
                      at android.content.res.Resources.loadXmlResourceParser(Resources.java:2351)
                      at android.content.res.Resources.getXml(Resources.java:1028)
                      at android.support.graphics.drawable.VectorDrawableCompat.create(VectorDrawableCompat.java:413)
                      at com.dijitalyayincim.cekmekoy.cekmekoy_web.AboutPage.createItem(AboutPage.java:360)
                      at com.dijitalyayincim.cekmekoy.cekmekoy_web.AboutPage.addItem(AboutPage.java:243)
                      at com.dijitalyayincim.cekmekoy.cekmekoy_web.AboutPage.addEmail(AboutPage.java:61)
                      at com.dijitalyayincim.cekmekoy.cekmekoy_web.MainActivity.onOptionsItemSelected(MainActivity.java:58)
                      at android.app.Activity.onMenuItemSelected(Activity.java:2644)
                      at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:406)
                      at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:195)
                      at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:103)
                      at android.support.v7.app.AppCompatDelegateImplV9.onMenuItemSelected(AppCompatDelegateImplV9.java:667)
                      at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:810)
                      at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
                      at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:957)
                      at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:947)
                      at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:616)
                      at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:153)
                      at android.view.View.performClick(View.java:4442)
                      at android.view.View$PerformClick.run(View.java:18473)
                      at android.os.Handler.handleCallback(Handler.java:733)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:136)
                      at android.app.ActivityThread.main(ActivityThread.java:5105)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:515)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
                      at dalvik.system.NativeStart.main(Native Method)




________________________________

**Comment by bahmet** [comment]
hello,
i used this 
`// Gradle Plugin 2.0+  
 android {  
   defaultConfig {  
     vectorDrawables.useSupportLibrary = true  
    }  
 }  `

and worked  :)
