### ISSUE TITLE
Add call us at (with phone icon)

### ISSUE THREAD

**Issue by MudasirBhutto** [medyo/android-about-page#89]
Hi there,

This is very nice library, and I am using it since last year. Thank you.

I want to request you add one more contact via phone element within this library. I tried to add it my self but on some devices it is giving exception of ResurceNotFound.

        Element callUsAt = new Element();
        callUsAt.setIcon(R.drawable.phone);
        callUsAt.setTitle("Call us at: +92 (021) 35302095");

java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2214)
  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2264)
  at android.app.ActivityThread.access$600(ActivityThread.java:144)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1259)
  at android.os.Handler.dispatchMessage(Handler.java:99)
  at android.os.Looper.loop(Looper.java:137)
  at android.app.ActivityThread.main(ActivityThread.java:5152)
  at java.lang.reflect.Method.invokeNative(Native Method:0)
  at java.lang.reflect.Method.invoke(Method.java:525)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:744)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
  at dalvik.system.NativeStart.main(Native Method:0)
Caused by: android.content.res.Resources$NotFoundException: 
  at android.content.res.Resources.loadXmlResourceParser(Resources.java:2398)
  at android.content.res.Resources.loadXmlResourceParser(Resources.java:2353)
  at android.content.res.Resources.getXml(Resources.java:1002)
  at android.support.graphics.drawable.VectorDrawableCompat.create(VectorDrawableCompat.java:586)
  at mehdi.sakout.aboutpage.AboutPage.createItem(AboutPage.java:360)
  at mehdi.sakout.aboutpage.AboutPage.addItem(AboutPage.java:243)
  at com.tapmad.tapmadtv.AboutActivity.onCreate(AboutActivity.java:74)
  at android.app.Activity.performCreate(Activity.java:5161)
  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2178)

**Comment by bolokoz** [comment]
you should use 
callUsAt.**setIconDrawable**(R.drawable.phone);

**Comment by MudasirBhutto** [comment]
Thank You Bolokoz

**Comment by edwinmugendi** [comment]
Below is a suggestion for the code to add an element that enables users to open the phone dialer with a preset phone number

```
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

       
        String phone = "+254722906835";

        View aboutPage = new AboutPage(this)
                .isRTL(false)
                //.setCustomFont(String) // or Typeface
                .setImage(R.drawable.login_logo)

                //.addItem(versionElement)
               // .addItem(adsElement)
                .addEmail("info@sapamatech.com")
                .addItem(getPhoneElement(phone))
                .addWebsite("https://sapamacash.com/")
                .addFacebook("sapamatech")
                .addTwitter("sapamatech")
                .addYoutube("UCV-sIbWJ5HpO0qk6Hp7Sjfw")
               // .addItem(getCopyRightsElement())
                //.addPlayStore("com.ideashower.readitlater.pro")
                //.addGitHub("medyo")
                //.addInstagram("medyo80")
                .create();

        setContentView(aboutPage);

    }

    /**
     * S# getPhoneElement() function
     *
     * Get Phone Element
     *
     * @param phone
     *
     * @return Element
     * */
    Element getPhoneElement(String phone) {
        Element copyRightsElement = new Element();
        final String phoneTitle = "Call us";
        copyRightsElement.setTitle(phoneTitle);
        copyRightsElement.setIconDrawable(R.drawable.ic_phone);
        copyRightsElement.setAutoApplyIconTint(true);
        copyRightsElement.setIconTint(mehdi.sakout.aboutpage.R.color.about_item_icon_color);
        copyRightsElement.setIconNightTint(android.R.color.white);
        copyRightsElement.setGravity(Gravity.LEFT);
        copyRightsElement.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Intent intent = new Intent(Intent.ACTION_DIAL);
                intent.setData(Uri.parse("tel:"+phone));
                startActivity(intent);
            }
        });

        return copyRightsElement;
    }  
}
```
